### ISSUE TITLE
Тесты не в той папке

### ISSUE THREAD

**Issue by boris-dev** [gutop84/liga-internship#2]
https://github.com/gutop84/liga-internship/blob/894c2a75d5b492bbd3c6f4dd479750702904284f/javacore-song-task/src/main/java/ru/liga/AppTest.java#L10

Должны быть в папке test
![image](https://user-images.githubusercontent.com/2234873/77325298-1f092080-6d29-11ea-98e9-928f1e6741c7.png)

**Comment by gutop84** [comment]
Перемещено
