### ISSUE TITLE
Именования

### ISSUE THREAD

**Issue by boris-dev** [gutop84/liga-internship#3]
Переменные с маленькой буквы
https://github.com/gutop84/liga-internship/blob/894c2a75d5b492bbd3c6f4dd479750702904284f/javacore-song-task/src/main/java/ru/liga/songtask/domain/SimpleMidiFile.java#L92

Не должно быть слов New и Old в названиях (если это относится именно к коду). Все названия должны быть приближены к бизнесу.
https://github.com/gutop84/liga-internship/blob/894c2a75d5b492bbd3c6f4dd479750702904284f/javacore-song-task/src/main/java/ru/liga/AppTestNew.java#L18

Слово Class тоже странное, ведь в java всё классы
https://github.com/gutop84/liga-internship/blob/894c2a75d5b492bbd3c6f4dd479750702904284f/javacore-song-task/src/main/java/ru/liga/songtask/util/ChangeClass.java#L17

Методы с маленькой буквы
https://github.com/gutop84/liga-internship/blob/894c2a75d5b492bbd3c6f4dd479750702904284f/javacore-song-task/src/main/java/ru/liga/songtask/analizismidi/AnalysisDuration.java#L25

**Comment by gutop84** [comment]
Переименовано
