### ISSUE TITLE
Смешение ответственности + не используем возвращаемый тип

### ISSUE THREAD

**Issue by boris-dev** [gutop84/liga-internship#4]
https://github.com/gutop84/liga-internship/blob/894c2a75d5b492bbd3c6f4dd479750702904284f/javacore-song-task/src/main/java/ru/liga/App.java#L82

Несколько классов по анализу. Они делают бизнес-вывод внутри метода, а то что возвращается не используется. Нужно разделить эту ответственность

**Comment by gutop84** [comment]
Теперь ничего не возвращаем.
(Зато храним в себе)
